language: objective-c
osx_image: xcode8
script: 
    xctool -project ACEViewSwift.xcodeproj -scheme ACEViewSwift -sdk macosx10.11 -destination arch=x86_64 -configuration Debug ONLY_ACTIVE_ARCH=NO test
