language: swift
osx_image: xcode9.1
script: 
    xcodebuild clean build test -project ACEViewSwift.xcodeproj -scheme ACEViewSwift -sdk macosx -destination arch=x86_64 -configuration Debug ONLY_ACTIVE_ARCH=NO
